## Data Cleaning

In [13]:
import pandas as pd

df = pd.read_csv('data/sensor.csv')

In [14]:
df.head()

,Unnamed: 0,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,...,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,...,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,...,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL

In [15]:
# Rename first column if needed
if 'Unnamed: 0' in df.columns:
    df = df.rename(columns={'Unnamed: 0': 'row_id'})

print(f'Loaded: {df.shape[0]:,} rows, {df.shape[1]} columns')

Loaded: 220,320 rows, 55 columns

In [16]:
# Convert timestamp & sort
df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values('timestamp').reset_index(drop=True)

In [17]:
# Inspect and drop completely empty sensor(s)
empty_sensors = [col for col in df.columns if df[col].isnull().all()]
print(f'Empty sensors: {empty_sensors}')
df = df.drop(columns=empty_sensors + ['row_id'], errors='ignore')

Empty sensors: ['sensor_15']

In [19]:
# Fill missing values (forward fill, then backward fill)
df = df.ffill().bfill()

In [20]:
# Add machine_id (for pipeline scalability)
df['machine_id'] = 1

In [22]:
# Reorder columns
cols = ['machine_id', 'timestamp'] + [c for c in df.columns if c not in ['machine_id', 'timestamp']]
df = df[cols]

In [23]:
# Save cleaned dataset as Parquet
df.to_parquet('data/processed_sensor_data.parquet', index=False)

In [25]:
# Summary stats
print(f'\nFinal shape   : {df.shape}')
print(f'Date range    : {df["timestamp"].min().date()}  to  {df["timestamp"].max().date()}')
print(f'Remaining NaNs: {df.isnull().sum().sum()}')

Final shape   : (220320, 54)
Date range    : 2018-04-01  to  2018-08-31
Remaining NaNs: 0

In [27]:
# class distribution
if 'machine_status' in df.columns:
    print('\nClass distribution:')
    vc = df['machine_status'].value_counts()
    for status, count in vc.items():
        print(f'  {status:<12}  {count:>7,}  ({count / len(df):.2%})')

Class distribution:
  NORMAL        205,836  (93.43%)
  RECOVERING     14,477  (6.57%)
  BROKEN              7  (0.00%)

## DB

In [1]:
import pandas as pd

df = pd.read_csv('data/sensor.csv')

In [2]:
df.head()

,Unnamed: 0,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,...,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,...,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,...,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL

In [3]:
df.dtypes

Unnamed: 0          int64
timestamp             str
sensor_00         float64
sensor_01         float64
sensor_02         float64
sensor_03         float64
sensor_04         float64
sensor_05         float64
sensor_06         float64
sensor_07         float64
sensor_08         float64
sensor_09         float64
sensor_10         float64
sensor_11         float64
sensor_12         float64
sensor_13         float64
sensor_14         float64
sensor_15         float64
sensor_16         float64
sensor_17         float64
sensor_18         float64
sensor_19         float64
sensor_20         float64
sensor_21         float64
sensor_22         float64
sensor_23         float64
sensor_24         float64
sensor_25         float64
sensor_26         float64
sensor_27         float64
sensor_28         float64
sensor_29         float64
sensor_30         float64
sensor_31         float64
sensor_32         float64
sensor_33         float64
sensor_34         float64
sensor_35         float64
sensor_36         float64
sensor_37         float64
sensor_38         float64
sensor_39         float64
sensor_40         float64
sensor_41         float64
sensor_42         float64
sensor_43         float64
sensor_44         float64
sensor_45         float64
sensor_46         float64
sensor_47         float64
sensor_48         float64
sensor_49         float64
sensor_50         float64
sensor_51         float64
machine_status        str
dtype: object

In [4]:
df.shape

(220320, 55)

In [5]:
from sqlalchemy import create_engine

In [7]:
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/sensor_data')

In [8]:
print(pd.io.sql.get_schema(df, name='whole_sensor_data', con=engine))

CREATE TABLE whole_sensor_data (
	"Unnamed: 0" BIGINT,
	timestamp TEXT,
	sensor_00 FLOAT(53),
	sensor_01 FLOAT(53),
	sensor_02 FLOAT(53),
	sensor_03 FLOAT(53),
	sensor_04 FLOAT(53),
	sensor_05 FLOAT(53),
	sensor_06 FLOAT(53),
	sensor_07 FLOAT(53),
	sensor_08 FLOAT(53),
	sensor_09 FLOAT(53),
	sensor_10 FLOAT(53),
	sensor_11 FLOAT(53),
	sensor_12 FLOAT(53),
	sensor_13 FLOAT(53),
	sensor_14 FLOAT(53),
	sensor_15 FLOAT(53),
	sensor_16 FLOAT(53),
	sensor_17 FLOAT(53),
	sensor_18 FLOAT(53),
	sensor_19 FLOAT(53),
	sensor_20 FLOAT(53),
	sensor_21 FLOAT(53),
	sensor_22 FLOAT(53),
	sensor_23 FLOAT(53),
	sensor_24 FLOAT(53),
	sensor_25 FLOAT(53),
	sensor_26 FLOAT(53),
	sensor_27 FLOAT(53),
	sensor_28 FLOAT(53),
	sensor_29 FLOAT(53),
	sensor_30 FLOAT(53),
	sensor_31 FLOAT(53),
	sensor_32 FLOAT(53),
	sensor_33 FLOAT(53),
	sensor_34 FLOAT(53),
	sensor_35 FLOAT(53),
	sensor_36 FLOAT(53),
	sensor_37 FLOAT(53),
	sensor_38 FLOAT(53),
	sensor_39 FLOAT(53),
	sensor_40 FLOAT(53),
	sensor_41 FLOAT(53),
	sensor_42 FLOAT(53),
	sensor_43 FLOAT(53),
	sensor_44 FLOAT(53),
	sensor_45 FLOAT(53),
	sensor_46 FLOAT(53),
	sensor_47 FLOAT(53),
	sensor_48 FLOAT(53),
	sensor_49 FLOAT(53),
	sensor_50 FLOAT(53),
	sensor_51 FLOAT(53),
	machine_status TEXT
)